version: '3.8'

services:
    stm-db:
        image: postgres:latest
        restart: always
        environment:
          POSTGRES_PASSWORD: secret
        ports:
          - '32672:5432'
        volumes:
          - 'stm-db:/var/lib/postgresql/data'
volumes:
  stm-db: null