version: '3.8'
services:
  nodecontroller:
    #image: log430/nodecontroller
    image: nodecontroller
    build:
      context: ../
      dockerfile: NodeController/NodeController/Dockerfile
    container_name: NodeController
    restart: always
    ports:
      - '${NODE_CONTROLLER_PORT}:80'
      - "4300-4310:4300-4310"
    environment:
      TEAM_NAME: '${TEAM_NAME}'
      USERNAME: '${USER}'
      GROUP: '${GROUP}'
      SECRET: '${SECRET}'
      INGRESS_ADDRESS: '${INGRESS_ADDRESS}'
      INGRESS_PORT: '${INGRESS_PORT}'
      SERVICES_ADDRESS: '${SERVICES_ADDRESS}'
      NODE_CONTROLLER_PORT: '${NODE_CONTROLLER_PORT}'
      MQ_SERVICE_NAME: EventStream
      CUSTOM_CONTAINER_PORTS_DISCOVERY: 5672
      BRIDGE_PORT: 32674
    depends_on:
      - event-store
  event-store:
    container_name: EventStream
    image: cluster_mq
    restart: always
    hostname: EventStream
    build:
      context: .
      dockerfile: Dockerfile    
    ports:
      - '32771:5672'
      - '30001:15672'
      - '25673:25672'
    environment:
      ID: EventStream
      RABBITMQ_ERLANG_COOKIE_FILE: /var/lib/rabbitmq/.erlang.cookie
    labels:
      Artifact_Category: Connector
      Replicas: EventStream, EventStream2, EventStream3, EventStream4, EventStream5

  routetimeprovider:
    container_name: RouteTimeProvider
    image: routetimeprovider
    restart: always
    build:
      context: ../
      dockerfile: RouteTimeProvider/RouteTimeProvider/Dockerfile
    environment:
      SERVICES_ADDRESS: '${SERVICES_ADDRESS}'
      NODE_CONTROLLER_PORT: '${NODE_CONTROLLER_PORT}'
      ID: RouteTimeProvider
      API_KEY: '${TOMTOM}'
    ports:
      - '32772:80'
    labels:
      ARTIFACT_CATEGORY: Computation
    depends_on:
      - nodecontroller
      - tripcomparator
      
  tripcomparator:
    container_name: TripComparator
    image: tripcomparator
    restart: always
    build:
      context: ../
      dockerfile: TripComparator/Controllers/Dockerfile
    environment:
      SERVICES_ADDRESS: '${SERVICES_ADDRESS}'
      NODE_CONTROLLER_PORT: '${NODE_CONTROLLER_PORT}'
      ID: Core.TripComparator
      MQ_SERVICE_NAME: EventStream
    ports:
      - '32773:80'
    labels:
      ARTIFACT_CATEGORY: Computation
      Replicas: 1
      Pod_Links: RouteTimeProvider, stm
    depends_on:
      - nodecontroller
  stm:
    container_name: STM
    image: stm
    restart: always
    build:
      context: ../
      dockerfile: STM/Controllers/Dockerfile
    environment:
      SERVICES_ADDRESS: '${SERVICES_ADDRESS}'
      NODE_CONTROLLER_PORT: '${NODE_CONTROLLER_PORT}'
      ID: STM
      API_KEY: '${STM}'
    ports:
      - '32774:80'
    labels:
      ARTIFACT_CATEGORY: Computation
    depends_on:
      - nodecontroller
      - tripcomparator

  