version: '3.8'
x-variables:
  SERVICES_ADDRESS: '10.194.33.150'
services:
  ui:
    container_name: UI
    build:
      context: ../UI
      dockerfile: Dockerfile
    image: ui:latest
    environment:
      INGRESS_PORT: '${INGRESS_PORT}'
      HOST: '${SERVICES_ADDRESS}'
    ports:
      - 32668:80
  ingress:
    image: ingress
    container_name: Ingress
    restart: always
    ports:
      - '32669:80'
    build:
      context: ../
      dockerfile: Ingress/Ingress/Dockerfile
    environment:
      NODE_STATE_STORAGE_PORT: 32670
      NODE_STATE_STORAGE_TOKEN: 'ejq_NUBcGGO2m20d5eKv4J1d-WvyEEfXUt4FGATZZCFSgARiCHHmIOJg_V2X9-Sn7RtDx5vSxc5XwKnRU5k89A=='
      AUTH_SERVICE_PORT: 32671
      SERVICES_ADDRESS: '${SERVICES_ADDRESS}'
      BRIDGE_PORT: 32674
    depends_on:
      - bridge
  node-state-time-serie-storage:
    image: 'influxdb:latest'
    container_name: NodeStateTimeSerieStorage
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=guest
      - DOCKER_INFLUXDB_INIT_PASSWORD=guest-pass
      - DOCKER_INFLUXDB_INIT_ORG=ets
      - DOCKER_INFLUXDB_INIT_BUCKET=NotNeeded
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ejq_NUBcGGO2m20d5eKv4J1d-WvyEEfXUt4FGATZZCFSgARiCHHmIOJg_V2X9-Sn7RtDx5vSxc5XwKnRU5k89A==
      - INFLUXD_LOG_LEVEL=error
    ports:
      - '32670:8086'
    volumes:
      - 'influxdb-data:/var/lib/influxdb2'
      - 'influxdb-config:/etc/influxdb2'
  authservice:
    image: authservice
    container_name: AuthService
    restart: always
    ports:
      - '32671:80'
    build:
      context: ../
      dockerfile: AuthService/AuthService/Dockerfile
    environment:
      POSTGRES_PORT: 32672
      SERVICES_ADDRESS: '${SERVICES_ADDRESS}'
  userdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - '32672:5432'
    volumes:
      - 'user-db:/var/lib/postgresql/data'

  adminer:
    image: adminer
    restart: always
    ports:
      - '32673:8080'
  bridge:
    container_name: BridgePortainerLocal
    image: 'rabbitmq:3.12-management'
    restart: always
    ports:
      - '32674:5672'
      - '32675:15672'
volumes:
  influxdb-data: null
  influxdb-config: null
  user-db: null
