version: '3.8'
x-conf:
  - env:
      - 'http://+:80'
      - EventStream
  - vol:
      - '${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro'
      - '${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro'
x-variables:
  SERVICES_ADDRESS: '${SERVICES_ADDRESS}'
  NODE_CONTROLLER_PORT: '${NODE_CONTROLLER_PORT}'
  ASPNETCORE_URLS: 'http://+:80'
services:
  #ui:
  #  build:
  #    context: ../
  #    dockerfile: UI/Dockerfile
  #  image: ui:latest
  #  environment:
  #    INGRESS_PORT: '${INGRESS_PORT}'
  #  ports:
  #    - 32668:80
  ingress:
    image: ingress
    container_name: Ingress
    restart: always
    ports:
      - '${INGRESS_PORT}:80'
    build:
      context: ../
      dockerfile: Ingress/Ingress/Dockerfile
    environment:
      ASPNETCORE_URLS: 'http://+:80'
      NODE_STATE_STORAGE_PORT: 32670
      NODE_STATE_STORAGE_TOKEN: '3JrkkUBIkNxPyHE1OO2AHVsasuxPPCvC974DYjRqN2b5INp70SHearLEfTB8WDPcTye__4hlz54z6g_O-77D2g=='
      AUTH_SERVICE_PORT: 32671
      SERVICES_ADDRESS: '${SERVICES_ADDRESS}'
      BRIDGE_PORT: 32674
    volumes:
      - '${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro'
      - '${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro'
    depends_on:
      - bridge
  node-state-time-serie-storage:
    image: 'influxdb:latest'
    container_name: NodeStateTimeSerieStorage
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=guest
      - DOCKER_INFLUXDB_INIT_PASSWORD=guest-pass
      - DOCKER_INFLUXDB_INIT_ORG=ets
      - 'DOCKER_INFLUXDB_INIT_BUCKET=${GROUP}'
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=3JrkkUBIkNxPyHE1OO2AHVsasuxPPCvC974DYjRqN2b5INp70SHearLEfTB8WDPcTye__4hlz54z6g_O-77D2g==
      - INFLUXD_LOG_LEVEL=debug
    ports:
      - '32670:8086'
    labels:
      ARTIFACT_CATEGORY: Database
      ARTIFACT_NAME: NodeStateTimeSerieStorage
    volumes:
      - 'influxdb-data:/var/lib/influxdb2'
      - 'influxdb-config:/etc/influxdb2'
  authservice:
    image: authservice
    container_name: AuthService
    restart: always
    ports:
      - '32671:80'
    build:
      context: ../
      dockerfile: AuthService/AuthService/Dockerfile
    environment:
      ASPNETCORE_URLS: 'http://+:80'
      POSTGRES_PORT: 32672
      SERVICES_ADDRESS: '${SERVICES_ADDRESS}'
    x-develop:
      watch:
        - action: build
          path: AuthService/
    volumes:
      - '${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro'
      - '${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro'
  userdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - '32672:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - '32673:8080'
  bridge:
    container_name: BridgePortainerLocal
    image: 'rabbitmq:3.12-rc-management'
    restart: always
    ports:
      - '32674:5672'
      - '32675:15672'
#volumes:
#  influxdb-data: null
#  influxdb-config: null
