name: NuGet Generation

on:
  push:
    branches:
      - S20232-refonte-microservices
      
permissions:
    packages: write
    actions: write
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/DavidDaniel18/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        
          
      - name: Build solution and generate NuGet package
        run: |  
          cd ./microservices/CommunicatorNuget/CommunicatorNuget
          dotnet pack -c Release -o out  
      - name: Publish Nuget to GitHub registry
        run: dotnet nuget push **.nupkg -k ${GITHUB_TOKEN} -s https://nuget.pkg.github.com/DavidDaniel18/index.json --skip-duplicate --no-symbols 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

