name: NuGet Generation

on:
  push:
    branches:
      - S20232-refonte-microservices

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/DavidDaniel18/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        
          
      - name: Build solution and generate NuGet package
        run: |  
          cd ./microservices/CommunicatorNuget/CommunicatorNuget
          dotnet pack -c Release -o out  

      - name: Push Package to GitHub.com
        run: dotnet nuget push **.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/DavidDaniel18/index.json
